plugin: amazon.aws.aws_ec2
regions:
  - us-east-1
filters:
  instance-state-name: running
  "tag:Name":
    - aws-autoscale-stack-nginx
    - aws-autoscale-stack-app
keyed_groups:
  - key: tags.Role
    prefix: role
hostnames:
  - instance-id   # SSM connection requires instance IDs, not IPs
